
services:
  - type: web
    name: ragnatales-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PORT=10000 python main.py
    envVars:
      - key: PORT
        value: 10000
    buildpacks:
      - url: heroku/python
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
