services:
  - type: web
    name: ragnatales-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    buildpacks:
      - url: heroku/python
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
