services:
  - type: web
    name: ragnatales-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x start_bot.sh
    startCommand: PORT=10000 ./start_bot.sh
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
