services:
  - type: web
    name: ragnatales-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium --with-deps
    startCommand: PORT=10000 python main.py
    envVars:
      - key: PORT
        value: 10000
    plan: free
