services:
  - type: web
    name: telegram-ragnatales-bot
    env: docker
    buildCommand: ""
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --threads 8"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://telegram-ragnatales-bot-1.onrender.com
      - key: IS_CONTAINER
        value: true
    healthCheckPath: /
